AWSTemplateFormatVersion: 2010-09-09
Description: >
  This creates the bucket to have the website

Parameters:
    EnvironmentName:
      Description: environment name
      Type: String

Resources:

    UagramBucketS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 809061358119-udagram-bucket
      DeletionPolicy: Delete
    UdagramRolIAM:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "${EnvironmentName}-Udagram-Role"
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"

    UdagramPolicies:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: !Sub "${EnvironmentName}-Udagram-Policies"
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 
            - "ec2:DescribeAddresses"
            - "ec2:AllocateAddress"
            - "ec2:DescribeInstances"
            - "ec2:AssociateAddress"
            - "ssm:Get*"
            - "s3:Get*"
            Resource: '*'
        Roles:
        - !Ref UdagramRolIAM
      
    UdagramInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Path: "/"
        Roles:
        - !Ref UdagramRolIAM