AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the server

Parameters:
    EnvironmentName:
      Description: environment name
      Type: String

    WebImageAMI:
      Description: Amazon machine "WebImageAMI"
      Type: String

    WebGroupMinSize:
      Description: EC2 Minimum number of instances
      Type: String

    WebGroupMaxSize:
      Description: EC2 Maximum number of instances
      Type: String

    WebGroupDesiredSize:
      Description: EC2 Required numbers to be deloyed
      Type: String

    KeyPair:
      Description: Key Pair ssh Name
      Type: String

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows traffic into the application
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ssh 
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  GtUdagramLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          cd /var/www/html
          rm index.html
          aws s3 cp index.html s3://809061358119-udagram-bucket
          systemctl start apache2.service
      ImageId:
        Ref: WebImageAMI
      SecurityGroups:
      - Ref: WebServerSecGroup
      InstanceType: t3.medium
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
          DeleteOnTermination: true

  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub "${EnvironmentName}-PRIV-NETS"
      LaunchConfigurationName:
        Ref: GtUdagramLaunchConfig
      DesiredCapacity:
        Ref: WebGroupDesiredSize
      MinSize:
        Ref: WebGroupMinSize
      MaxSize:
        Ref: WebGroupMaxSize
      TargetGroupARNs:
      - Ref: WebAppTargetGroup
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Subnets:
      - Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-PUB-SUB1"
      - Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-PUB-SUB2"
      SecurityGroups:
      - Ref: LBSecGroup
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP
  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebAppTargetGroup'
        Conditions:
        - Field: path-pattern
          Values: [/]
        ListenerArn: !Ref 'Listener'
        Priority: 1
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-VPCID"
      

Outputs:
  LoadBalancerDNSName:
    Description: Web app DNS name
    Value:
      Fn::Join:
        - ""
        - - "http://"
          - Fn::GetAtt: WebAppLB.DNSName
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-DNS-NAME"
